### ISSUE TITLE
Building for windows says SQLite3.UWP is invalid reference

### ISSUE THREAD

**Issue by Gillardo** [litehelpers/Cordova-sqlite-help#30]
When i create my cordova app and add the windows platform, upon opening the project i get a warning message next to the SQLite3.UWP reference under my CordovaApp project.  I cannot add any more references to this project, unless i remove the reference.  Upon trying to re-add the reference i get the message

![image](https://user-images.githubusercontent.com/7406381/29287132-50cf9ad6-812c-11e7-9019-65dc80cdb2d0.png)

Previous projects that i used, must of used a different version of SQLite3, as it used to be 2 separate projects, not this SQLite.UWP project. 

Also, i need to create a Windows Runtime Component class library as i need to run background tasks, and i cannot add a reference to SQLite3.UWP project to my class library?  Is this something special? Why can i not reference it in either projects?

I need to add a reference to my CordovaApp project to my new class library, and use SQLite in my class library....

Any help much appreciated

NOTE:  I have also updated all my projects to run on x86

![image](https://user-images.githubusercontent.com/7406381/29287462-73ef2076-812d-11e7-8d5f-ff0257274790.png)

**Comment by brody2consult** [comment]
My apologies for the delay. I am afraid that I really do not understand. A demo project, ideally based on <https://github.com/brodybits/cordova-sqlite-storage-starter-app> or <https://github.com/brodybits/cordova-sqlite-test-app> would be really helpful.

**Comment by brody2consult** [comment]
Closing due to lack of explanation.
