### ISSUE TITLE
Disable WAL-mode File Format in sqlite for Android 9

### ISSUE THREAD

**Issue by avarelahn** [litehelpers/Cordova-sqlite-help#69]
Hello, I have a problem with my application in the android pie version.
When executing the select using this.sqlite.create () to my database, I get the error: code: 5
message: "sqlite3_prepare_v2 failure: no such table: products"
Apparently I created the database but not the table, in previous versions my application worked great, but in the Pie version or greater it gives me this problem. I read that Android 9 introduces an activated default functionality called WAL (write-ahead logging) but I don't know how to disable this in my code, someone could help me with this, I would appreciate it.

**Comment by brody2consult** [comment]
This is only an issue in case the database is opened with `androidDatabaseImplementation: 'system'` on Android and is discussed in <https://github.com/xpbrew/cordova-sqlite-storage/issues/887>.
